### PR TITLE
add markdown file to help with debugging

### PR DESCRIPTION
**Pull request by lachlan-roberts**

### CODE REVIEW

**Comment by maigovannon** [comment]
Please wait while we create an empty file for the same as the `copy-bara` doesn't sync seamlessly top-level new files.

**Comment by maigovannon** [comment]
The commit has been pushed: https://github.com/GoogleCloudPlatform/appengine-java-standard/commit/7ef6c65e9a5e6d4f160b8efe8428770cb6531907. Please pull in these latest changes and merge in the PR.

**Comment by lachlan-roberts** [comment]
@maigovannon I merged from main.

**Comment by ludoch** [comment]
@maigovannon will learn and do the approval and ready_to_pull workflow so this can be integrated in internal repo then merged in gh. Thanks!

**Review by maigovannon — APPROVED** [review]

**Pull request merged**
