### PR TITLE
Issue #16 fix multithread build

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Review by lachlan-roberts — APPROVED** [review]
Thanks, fixed the problem for me so looks good.

**Comment by ludoch** [comment]
Adding ready to pull tag to start the process of testing this from google side. Do not merge manually.

**Comment by ludoch** [comment]
git actions seem to be stuck on 8 and 17.... Why?

**Comment by ludoch** [comment]
Sorry, our internal checks see 3 issues:
license content in the cmd file and the property file, please change to correct header as seen in other files with these types

and more important: we cannot import binary jar files anymore in our internal repository, so please also change to avoid adding a jar file in the PR.
Thanks!

**Comment by olamy** [comment]
> Sorry, our internal checks see 3 issues: license content in the cmd file and the property file, please change to correct header as seen in other files with these types
> 

those files have been generated using `mvn --errors --batch-mode --show-version org.apache.maven.plugins:maven-wrapper-plugin:3.1.0:wrapper -Dmaven=3.8.6`
Anyway I have restored the content from `main` branch.

> and more important: we cannot import binary jar files anymore in our internal repository, so please also change to avoid adding a jar file in the PR. Thanks!

sure I have restored previous as new version of maven wrapper is now using a jar.

**Pull request merged**
